import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import {} from "next/font/google";
import "./globals.css";

const cormorant_garamond = Cormorant_Garamond({
  weight: ["400", "600", "700", "500"],
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-[#FAFAFA] ${geistSans.variable} ${geistMono.variable} ${cormorant_garamond.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
